---
installCRDs: true
redis-ha:
  enabled: true
  metrics:
    enabled: true
redis:
  enabled: false
controller:
  enableStatefulSet: true
  logFormat: json
  metrics:
    enabled: true
server:
  replicas: 2
  logFormat: json
  env:
    - name: ARGOCD_API_SERVER_REPLICAS
      value: '2'
  # certificate:
  #   enabled: true
  #   domain: argocd.gcp.totalbattle.tech
  #   issuer:
  #     kind: ClusterIssuer
  #     name: totalbattle-tech-le
  # ingress:
  #   enabled: true
  #   annotations:
  #     cert-manager.io/cluster-issuer: totalbattle-tech-le
  #     nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  #     nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  #   ingressClassName: internal-nginx
  #   hosts:
  #     - argocd.gcp.totalbattle.tech
  #   tls:
  #     - hosts:
  #       - argocd.gcp.totalbattle.tech
  #       secretName: argocd-server-tls
  metrics:
    enabled: true
  admin.enabled: false
  rbacConfigCreate: false
  configEnabled: false
  dex.config: |
    extraVolumes:
      # - mountPath: /tmp
      #   name: dexconfig
      - mountPath: /tmp/oidc
        name: google-json
        readOnly: true
    extraVolumes:
      - emptyDir: {}
        name: static-files
      - emptyDir: {}
        name: dexconfig
      - name: google-json
        secret:
          defaultMode: 420
          secretName: argocd-google-groups-json
repoServer:
  replicas: 2
  logFormat: json
  metrics:
    enabled: false
# url: https://argocd.gcp.totalbattle.tech
