---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: node-exporter
  namespace: argocd
  labels:
    docker-desktop/cluster: in-cluster
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'node-exporter-{{name}}'
      namespace: argocd
      labels:
        docker-desktop/cluster: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://prometheus-community.github.io/helm-charts
        chart: prometheus-node-exporter
        targetRevision: 3.0.0
        helm:
          releaseName: prometheus-node-exporter
          values: |
            ---
            hostRootFsMount:
              enabled: false
      destination:
        name: '{{name}}'
        namespace: monitoring
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
