---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: node-exporter
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: 'node-exporter-{{name}}'
      namespace: monitoring
    spec:
      project: default
      source:
        repoURL: https://prometheus-community.github.io/helm-charts
        chart: prometheus-node-exporter
        targetRevision: 3.0.0
        helm:
          releaseName: prometheus-node-exporter
      destination:
        name: '{{name}}'
        namespace: monitoring
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
