---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-sets
  namespace: argocd
  labels:
    docker-desktop/cluster: in-cluster
spec:
  project: default
  source:
    repoURL: https://github.com/zlkn/test-applicationset.git
    path: application-sets
    targetRevision: HEAD
  destination:
    name: in-cluster
  syncPolicy:
    automated: {}
